[package]
name = "a50-dock-switch"
version = "0.1.0"
edition = "2021"

[lib]
name = "a50_dock_switch_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusb = "0.9"
chrono = "0.4"
windows = { version = "0.58", features = [
    "Win32_System_Registry",
] }
